name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  schedule:
    - cron: '40 4 * * *'   # every day at 4:40
  pull_request:

jobs:
  build:
    name: "Build"

    strategy:
      matrix:
        platform: [
          ubuntu-latest,
          macos-latest,
          windows-latest
        ]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15

    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v1

    - name: Install Rustup (macOS)
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo ::add-path::$HOME/.cargo/bin
      if: runner.os == 'macOS'

    - name: Set Rustup profile to minimal
      run: rustup set profile minimal

    - name: Install musl target on Linux
      run: |
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get install musl-tools musl-dev
      if: runner.os == 'Linux'

    - name: "Print Rust Version"
      run: |
        rustc -Vv
        cargo -Vv

    - name: "Run cargo build"
      run: cargo build

    - name: "Run cargo test"
      run: cargo test

    - name: "Deny Warnings"
      run: cargo build
      env:
        RUSTFLAGS: "-D warnings"

    - name: "Install it"
      run: cargo install --path . --debug

    - name: "Upload Artifact"
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.name }}-bootimage
        path: ~/.cargo/bin/bootimage

  test:
    name: "Test"

    strategy:
      matrix:
        platform: [
          ubuntu-latest,
          macos-latest,
          windows-latest
        ]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15

    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v1

    - name: "Download Bootimage Artifact"
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.name }}-bootimage
        path: ~/.cargo/bin/bootimage

    - name: Install Rustup (macOS)
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo ::add-path::$HOME/.cargo/bin
      if: runner.os == 'macOS'

    - name: "Install Rustup Components"
      run: rustup component add rust-src llvm-tools-preview
    - name: "Install cargo-xbuild"
      run: cargo install cargo-xbuild --debug

     # install QEMU
    - name: Install QEMU (Linux)
      run: |
        sudo apt update
        sudo apt install qemu-system-x86
      if: runner.os == 'Linux'
    - name: Install QEMU (macOS)
      run: brew install qemu
      if: runner.os == 'macOS'
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
        HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
        HOMEBREW_NO_INSTALL_CLEANUP: 1
    - name: Install Scoop (Windows)
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        echo ::add-path::$HOME\scoop\shims
      if: runner.os == 'Windows'
      shell: pwsh
    - name: Install QEMU (Windows)
      run: scoop install qemu
      if: runner.os == 'Windows'
      shell: pwsh

    - name: "Print QEMU Version"
      run: qemu-system-x86_64 --version

    - name: 'Build "basic" Kernel'
      run: cargo bootimage --target ../x86_64-bootimage-example-kernels.json
      working-directory: example-kernels/basic

    - name: 'Run QEMU with "basic" Kernel'
      run: |
        qemu-system-x86_64 -drive format=raw,file=target/x86_64-bootimage-example-kernels/debug/bootimage-basic.bin -device isa-debug-exit,iobase=0xf4,iosize=0x04 -display none
        if [ $? -eq 103 ]; then (exit 0); else (exit 1); fi
      shell: bash
      working-directory: example-kernels

    - name: 'Run `cargo xrun` for "runner" kernel'
      run: |
        cargo xrun
        if [ $? -eq 109 ]; then (exit 0); else (exit 1); fi
      shell: bash
      working-directory: example-kernels/runner

    - run: cargo xtest -Z doctest-xcompile
      working-directory: example-kernels/runner-doctest
      name: 'Run `cargo xtest -Z doctest-xcompile` for "runner-doctest" kernel'

    - run: cargo xtest
      working-directory: example-kernels/runner-test
      name: 'Run `cargo xtest` for "runner-test" kernel'

  check_formatting:
    name: "Check Formatting"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v1
    - run: rustup toolchain install nightly --profile minimal --component rustfmt
    - run: cargo +nightly fmt -- --check

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - run: rustup toolchain install nightly --profile minimal --component clippy
    - run: cargo +nightly clippy -- -D warnings
